spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pokemon-tcg-sdk
    username: root #${USERNAME:root}
    password: Admin@123 #${PASSWORD:Admin@123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

config:
  language: ${LANGUAGE_DEFAULT:pt-BR}
files:
  card:
    pathFile: ${CARD_PATH:static/data/cards/}
    indexFile: ${CARD_FILENAME:index.json}
  set:
    pathFile: ${POKEMON_SET_PATH:static/data/pokemon-set/}
    fileName: ${POKEMON_SET_FILENAME:pokemon-set}
    indexFile: ${POKEMON_SET_INDEX:index.json}