spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pokemon-tcg-sdk
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

language: ${LANGUAGE:pt-BR}}